version: '3.7'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
